version: "3.9"
services:
  web: # application web service
    build:
      context: .
      dockerfile: Dockerfile
    image: registryexplain.azurecr.io/webexplain
    container_name: webexplain
    ports:
      - "80:80"
    command: ['python', 'app.py']
    depends_on:
      - database
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=0000
      - DB_DATABASE=postgres
      - DB_HOST=database

  database: # database service configuration
    image: postgres:15
    container_name: explaindatabase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: # data volumes from database postgresql
    #driver: azure_file
    #driver_opts:
     #share_name: myfileshare
     #storage_account_name: mystorageaccountexplain
