apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: explain
  name: dash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explain-app
  template:
    metadata:
      labels:
        app: explain-app
    spec:
      containers:
      #app container
      - name: explain-app
        image: franck123/explain:explainApp
        args: ['python', 'app.py']
        ports:
        - containerPort: 8050
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:0000@postgres-service:5432/postgres"

      #database container
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: postgres-secret 
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc