apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: explain
  name: dash-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explain-app
  template:
    metadata:
      labels:
        app: explain-app
    spec:
      containers:
      - name: explain-app
        image: franck123/webexplain:latest
        args: ['python', 'app.py']
        ports:
        - containerPort: 8050
        env:
         #- name: DATABASE_URL
         # value: "postgresql://postgres:0000@postgres-service:5432/postgres"
         - name: POSTGRES_HOST
           value: postgres

         - name: POSTGRES_PORT
           value: "5432"

         - name: POSTGRES_DB
           value: postgres

         - name: POSTGRES_USER
           valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

         - name: POSTGRES_PASSWORD
           valueFrom:
                secretKeyRef:
                  name: postgres-secret 
                  key: POSTGRES_PASSWORD
        volumeMounts:
        - name: explain-app-pv
          mountPath: /var/lib/explain_app/data
      volumes:
      - name: explain-app-pv
        persistentVolumeClaim:
          claimName: myclaim

